#!/bin/bash

set -e

rm packer_virtualbox-iso_virtualbox.box || true
packer build -only virtualbox-iso base.json
vagrant box remove base || true
vagrant box add base packer_virtualbox-iso_virtualbox.box
