#!/bin/bash
# Thanks to Codeship (http://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior) for this script

set -e

rm packer_virtualbox-iso_virtualbox.box || true
packer build -only virtualbox-iso base.json
vagrant box remove base || true
vagrant box add base packer_virtualbox-iso_virtualbox.box
